const IMAGES = {
    image1: new URL('./IMG_4809.png', import.meta.url).href,
    image2: new URL('./IMG_4810.png', import.meta.url).href,
    image3: new URL('./IMG_4811.png', import.meta.url).href,
    image4: new URL('./IMG_4812.png', import.meta.url).href,
    image5: new URL('./IMG_4813.png', import.meta.url).href,
    image6: new URL('./IMG_4814.png', import.meta.url).href,
    image7: new URL('./IMG_4816.png', import.meta.url).href,
    image8: new URL('./IMG_4817.png', import.meta.url).href,
    image9: new URL('./IMG_4818.png', import.meta.url).href,
    image10: new URL('./IMG_4819.png', import.meta.url).href,
    image11: new URL('./IMG_4820.png', import.meta.url).href,
    image12: new URL('./IMG_4821.png', import.meta.url).href,
    image13: new URL('./IMG_4822.png', import.meta.url).href,
    image14: new URL('./IMG_4823.png', import.meta.url).href,
    image15: new URL('./IMG_5037 1.png', import.meta.url).href,
    image16: new URL('./IMG_5038 2.png', import.meta.url).href,
    image17: new URL('./IMG_5039 2.png', import.meta.url).href,
    image18: new URL('./IMG_5040 1.png', import.meta.url).href,
    image19: new URL('./IMG_5041 1.png', import.meta.url).href,
    image20: new URL('./IMG_5067 1.png', import.meta.url).href,
    image21: new URL('./IMG_5069 1.png', import.meta.url).href,
    image22: new URL('./IMG_5070 1.png', import.meta.url).href,
    image23: new URL('./IMG_5071 1.png', import.meta.url).href,
    image24: new URL('./IMG_5072 2.png', import.meta.url).href,
    image25: new URL('./IMG_5073 2.png', import.meta.url).href,
    image26: new URL('./IMG_5074 1.png', import.meta.url).href,
    image27: new URL('./IMG_5075 1.png', import.meta.url).href,
    image28: new URL('./Rectangle 73.png', import.meta.url).href,
}

export default IMAGES